import type {
  Signal,
  SignalIndex,
  ContentOpportunity,
  Brand24Mention,
  Brand24Stats,
  OuterSignalProfile,
  OuterSignalInsight,
  TrendPoint,
} from '../types';

// ── Signal Index Score ──
export const signalIndex: SignalIndex = {
  overall: 74,
  sentiment: 68,
  visibility: 81,
  engagement: 72,
  authority: 65,
  momentum: 79,
};

// ── Signals Feed ──
export const signals: Signal[] = [
  {
    id: 's1',
    source: 'brand24',
    type: 'mention',
    title: 'Featured in TechCrunch article on emerging tools',
    description: 'Your brand was mentioned positively in a TechCrunch roundup of innovative SaaS platforms gaining traction in Q1.',
    sentiment: 0.85,
    strength: 92,
    reach: 450000,
    timestamp: '2026-03-18T09:30:00Z',
    tags: ['press', 'tech', 'positive'],
    platform: 'TechCrunch',
    author: 'Sarah Chen',
  },
  {
    id: 's2',
    source: 'social',
    type: 'trend',
    title: 'Hashtag #SignalEar trending in marketing communities',
    description: 'Your branded hashtag saw a 340% increase in usage across Twitter/X and LinkedIn marketing communities.',
    sentiment: 0.72,
    strength: 85,
    reach: 128000,
    timestamp: '2026-03-18T08:15:00Z',
    tags: ['social', 'trending', 'marketing'],
    platform: 'Twitter/X',
  },
  {
    id: 's3',
    source: 'outersignal',
    type: 'opportunity',
    title: 'Enterprise segment showing high intent signals',
    description: 'OuterSignal enrichment reveals 23 enterprise accounts with buying signals — job postings for "brand monitoring" roles detected.',
    sentiment: 0.6,
    strength: 88,
    reach: 15000,
    timestamp: '2026-03-17T16:45:00Z',
    tags: ['enterprise', 'intent', 'opportunity'],
  },
  {
    id: 's4',
    source: 'brand24',
    type: 'competitor',
    title: 'Competitor launched new pricing tier',
    description: 'Brandwatch announced a new SMB pricing tier, potentially targeting your core audience segment.',
    sentiment: -0.3,
    strength: 76,
    reach: 85000,
    timestamp: '2026-03-17T14:20:00Z',
    tags: ['competitor', 'pricing', 'risk'],
    platform: 'Blog',
    author: 'Brandwatch Team',
  },
  {
    id: 's5',
    source: 'news',
    type: 'sentiment',
    title: 'Industry sentiment shifting toward AI-powered listening',
    description: 'News analysis shows a 45% increase in articles discussing AI-driven brand monitoring — aligns with your positioning.',
    sentiment: 0.55,
    strength: 70,
    reach: 320000,
    timestamp: '2026-03-17T11:00:00Z',
    tags: ['AI', 'industry', 'trend'],
  },
  {
    id: 's6',
    source: 'review',
    type: 'risk',
    title: 'Negative review cluster on G2',
    description: 'Three new reviews mention "onboarding complexity" — customer success team should address setup documentation.',
    sentiment: -0.65,
    strength: 60,
    reach: 12000,
    timestamp: '2026-03-16T19:30:00Z',
    tags: ['review', 'negative', 'onboarding'],
    platform: 'G2',
  },
  {
    id: 's7',
    source: 'outersignal',
    type: 'opportunity',
    title: 'Influencer partnership opportunity detected',
    description: 'Marketing influencer @ContentKing (280K followers) recently engaged with brand monitoring content — high affinity score.',
    sentiment: 0.45,
    strength: 82,
    reach: 280000,
    timestamp: '2026-03-16T15:10:00Z',
    tags: ['influencer', 'partnership', 'opportunity'],
    author: '@ContentKing',
    platform: 'LinkedIn',
  },
  {
    id: 's8',
    source: 'social',
    type: 'mention',
    title: 'Viral thread comparing brand listening tools',
    description: 'A Twitter thread comparing 5 brand listening tools received 2.3K retweets — your tool ranked #2 for "ease of use".',
    sentiment: 0.5,
    strength: 78,
    reach: 195000,
    timestamp: '2026-03-16T10:45:00Z',
    tags: ['comparison', 'viral', 'social'],
    platform: 'Twitter/X',
    author: '@MarketingMike',
  },
];

// ── Signal Index Trend ──
export const signalTrend: TrendPoint[] = [
  { date: '2026-03-04', value: 62 },
  { date: '2026-03-05', value: 64 },
  { date: '2026-03-06', value: 61 },
  { date: '2026-03-07', value: 66 },
  { date: '2026-03-08', value: 68 },
  { date: '2026-03-09', value: 65 },
  { date: '2026-03-10', value: 70 },
  { date: '2026-03-11', value: 72 },
  { date: '2026-03-12', value: 69 },
  { date: '2026-03-13', value: 73 },
  { date: '2026-03-14', value: 71 },
  { date: '2026-03-15', value: 74 },
  { date: '2026-03-16', value: 72 },
  { date: '2026-03-17', value: 76 },
  { date: '2026-03-18', value: 74 },
];

// ── Brand24 Data ──
export const brand24Stats: Brand24Stats = {
  totalMentions: 1847,
  positiveMentions: 1102,
  negativeMentions: 198,
  neutralMentions: 547,
  totalReach: 4200000,
  avgSentiment: 0.62,
  topSources: [
    { name: 'Twitter/X', count: 623 },
    { name: 'Reddit', count: 312 },
    { name: 'LinkedIn', count: 287 },
    { name: 'News Sites', count: 245 },
    { name: 'Blogs', count: 198 },
    { name: 'YouTube', count: 112 },
    { name: 'Forums', count: 70 },
  ],
  mentionTrend: [
    { date: '2026-03-04', count: 98 },
    { date: '2026-03-05', count: 112 },
    { date: '2026-03-06', count: 105 },
    { date: '2026-03-07', count: 134 },
    { date: '2026-03-08', count: 156 },
    { date: '2026-03-09', count: 123 },
    { date: '2026-03-10', count: 145 },
    { date: '2026-03-11', count: 167 },
    { date: '2026-03-12', count: 142 },
    { date: '2026-03-13', count: 178 },
    { date: '2026-03-14', count: 152 },
    { date: '2026-03-15', count: 189 },
    { date: '2026-03-16', count: 163 },
    { date: '2026-03-17', count: 201 },
    { date: '2026-03-18', count: 182 },
  ],
};

export const brand24Mentions: Brand24Mention[] = [
  {
    id: 'b1',
    content: 'Just tried Signal Ear for our Q1 brand audit — the signal index is a game changer for prioritizing content strategy.',
    source: 'Twitter/X',
    sourceUrl: '#',
    author: '@MarketingPro',
    sentiment: 'positive',
    reach: 34000,
    importance: 9,
    date: '2026-03-18T08:20:00Z',
    tags: ['product', 'praise'],
  },
  {
    id: 'b2',
    content: 'Comparing Signal Ear vs Brandwatch vs Mention — Signal Ear wins on UX but needs more integrations.',
    source: 'Reddit',
    sourceUrl: '#',
    author: 'u/saas_reviewer',
    sentiment: 'neutral',
    reach: 15000,
    importance: 8,
    date: '2026-03-17T22:15:00Z',
    tags: ['comparison', 'feedback'],
  },
  {
    id: 'b3',
    content: 'The onboarding for Signal Ear was confusing. Took 3 support tickets before I got my dashboard set up properly.',
    source: 'G2',
    sourceUrl: '#',
    author: 'Enterprise User',
    sentiment: 'negative',
    reach: 8000,
    importance: 7,
    date: '2026-03-17T14:30:00Z',
    tags: ['onboarding', 'support'],
  },
  {
    id: 'b4',
    content: 'Signal Ear\'s brand listening capabilities are impressive for the price point. Highly recommend for growing brands.',
    source: 'LinkedIn',
    sourceUrl: '#',
    author: 'James Rodriguez, CMO',
    sentiment: 'positive',
    reach: 52000,
    importance: 9,
    date: '2026-03-16T16:00:00Z',
    tags: ['recommendation', 'value'],
  },
  {
    id: 'b5',
    content: 'New blog post: How we used Signal Ear to increase our share of voice by 40% in 6 months.',
    source: 'Blog',
    sourceUrl: '#',
    author: 'GrowthHack Weekly',
    sentiment: 'positive',
    reach: 28000,
    importance: 8,
    date: '2026-03-15T10:00:00Z',
    tags: ['case-study', 'results'],
  },
];

// ── OuterSignal Data ──
export const outerSignalProfiles: OuterSignalProfile[] = [
  {
    id: 'os1',
    name: 'Sarah Chen',
    email: 's.chen@techcorp.io',
    company: 'TechCorp',
    title: 'VP of Marketing',
    industry: 'SaaS',
    interests: ['brand monitoring', 'content strategy', 'AI tools'],
    engagementScore: 92,
    socialProfiles: [
      { platform: 'LinkedIn', url: '#', followers: 12400 },
      { platform: 'Twitter/X', url: '#', followers: 8700 },
    ],
    enrichedAt: '2026-03-18T07:00:00Z',
  },
  {
    id: 'os2',
    name: 'Marcus Johnson',
    email: 'm.johnson@brandly.com',
    company: 'Brandly',
    title: 'Head of Growth',
    industry: 'Marketing Tech',
    interests: ['growth hacking', 'social listening', 'analytics'],
    engagementScore: 87,
    socialProfiles: [
      { platform: 'LinkedIn', url: '#', followers: 9800 },
      { platform: 'Twitter/X', url: '#', followers: 15200 },
    ],
    enrichedAt: '2026-03-17T15:30:00Z',
  },
  {
    id: 'os3',
    name: 'Emily Park',
    company: 'ScaleUp Inc',
    title: 'Director of Communications',
    industry: 'Enterprise Software',
    interests: ['PR', 'reputation management', 'crisis comms'],
    engagementScore: 78,
    socialProfiles: [
      { platform: 'LinkedIn', url: '#', followers: 6200 },
    ],
    enrichedAt: '2026-03-16T12:00:00Z',
  },
  {
    id: 'os4',
    name: 'David Kim',
    email: 'd.kim@ecomhub.co',
    company: 'EcomHub',
    title: 'CMO',
    industry: 'E-Commerce',
    interests: ['customer insights', 'brand perception', 'market research'],
    engagementScore: 84,
    socialProfiles: [
      { platform: 'LinkedIn', url: '#', followers: 18500 },
      { platform: 'Twitter/X', url: '#', followers: 22000 },
      { platform: 'YouTube', url: '#', followers: 5400 },
    ],
    enrichedAt: '2026-03-17T09:45:00Z',
  },
];

export const outerSignalInsights: OuterSignalInsight[] = [
  {
    id: 'oi1',
    type: 'audience_segment',
    label: 'Marketing Leaders at Scale-ups',
    description: 'VP/Director-level marketers at companies with 50-500 employees showing high brand monitoring intent.',
    confidence: 0.89,
    size: 342,
    profiles: ['os1', 'os2'],
  },
  {
    id: 'oi2',
    type: 'interest_cluster',
    label: 'AI-Powered Analytics Enthusiasts',
    description: 'Professionals actively researching AI-driven marketing and brand analytics tools.',
    confidence: 0.82,
    size: 567,
    profiles: ['os1', 'os4'],
  },
  {
    id: 'oi3',
    type: 'engagement_pattern',
    label: 'Weekly Content Consumers',
    description: 'Segment that engages with brand-related content 3-5 times per week across LinkedIn and Twitter.',
    confidence: 0.75,
    size: 891,
    profiles: ['os2', 'os3', 'os4'],
  },
  {
    id: 'oi4',
    type: 'demographic',
    label: 'Enterprise Decision Makers',
    description: 'C-suite and senior leaders at 1000+ employee companies evaluating brand listening solutions.',
    confidence: 0.91,
    size: 156,
    profiles: ['os3'],
  },
];

// ── Content Opportunities ──
export const contentOpportunities: ContentOpportunity[] = [
  {
    id: 'co1',
    title: 'Publish "AI Brand Monitoring" Thought Leadership Piece',
    description: 'Industry sentiment is shifting toward AI-powered listening. Capitalize on this trend with a definitive guide positioning Signal Ear as the leader.',
    priority: 'high',
    category: 'blog',
    estimatedImpact: 88,
    signals: ['s5', 's2'],
    suggestedActions: [
      'Draft a 2,000-word guide on AI in brand monitoring',
      'Include data from your Signal Index showing trend momentum',
      'Distribute via LinkedIn, Twitter, and email newsletter',
      'Pitch to marketing publications for syndication',
    ],
    status: 'new',
  },
  {
    id: 'co2',
    title: 'Launch Influencer Partnership with @ContentKing',
    description: 'High-affinity influencer detected by OuterSignal with 280K followers in your target demographic.',
    priority: 'high',
    category: 'social',
    estimatedImpact: 85,
    signals: ['s7'],
    suggestedActions: [
      'Reach out with a personalized pitch highlighting shared audience',
      'Offer a free premium trial + co-created content opportunity',
      'Plan a LinkedIn Live or Twitter Spaces collaboration',
      'Track campaign impact through Brand24 mentions',
    ],
    status: 'new',
  },
  {
    id: 'co3',
    title: 'Address Onboarding Friction with Video Series',
    description: 'Negative review cluster on G2 highlights onboarding pain. Turn this into content that solves the problem and improves perception.',
    priority: 'high',
    category: 'video',
    estimatedImpact: 76,
    signals: ['s6'],
    suggestedActions: [
      'Create a 5-part "Getting Started" video series',
      'Build an interactive product tour',
      'Update help documentation with visual guides',
      'Proactively share with new users during onboarding',
    ],
    status: 'new',
  },
  {
    id: 'co4',
    title: 'Competitive Comparison Landing Page',
    description: 'Viral comparison thread shows demand for tool comparisons. Create a definitive "Signal Ear vs. Competitors" page.',
    priority: 'medium',
    category: 'seo',
    estimatedImpact: 72,
    signals: ['s8', 's4'],
    suggestedActions: [
      'Create SEO-optimized comparison pages for top 5 competitors',
      'Include real user testimonials and data points',
      'Add interactive feature comparison tables',
      'Run targeted search ads on comparison keywords',
    ],
    status: 'new',
  },
  {
    id: 'co5',
    title: 'Enterprise Case Study Campaign',
    description: 'OuterSignal detected 23 enterprise accounts with buying signals. Create case studies to convert this segment.',
    priority: 'medium',
    category: 'pr',
    estimatedImpact: 80,
    signals: ['s3'],
    suggestedActions: [
      'Identify 3-5 existing enterprise customers for case studies',
      'Focus on ROI metrics and time-to-value',
      'Gate behind a lead form for nurture campaigns',
      'Distribute through ABM channels targeting detected accounts',
    ],
    status: 'new',
  },
  {
    id: 'co6',
    title: 'TechCrunch Momentum — PR Follow-up',
    description: 'Leverage the TechCrunch mention momentum with a targeted PR push to extend media coverage.',
    priority: 'medium',
    category: 'pr',
    estimatedImpact: 70,
    signals: ['s1'],
    suggestedActions: [
      'Prepare a press kit with latest metrics and growth story',
      'Pitch follow-up stories to 10 similar publications',
      'Create social proof assets from the TechCrunch mention',
      'Schedule a CEO interview or guest column opportunity',
    ],
    status: 'new',
  },
];

// ── Sentiment Distribution ──
export const sentimentDistribution = [
  { name: 'Positive', value: 60, color: '#10b981' },
  { name: 'Neutral', value: 29, color: '#94a3b8' },
  { name: 'Negative', value: 11, color: '#f43f5e' },
];

// ── Source Distribution ──
export const sourceDistribution = [
  { name: 'Social Media', value: 42, color: '#6366f1' },
  { name: 'News & Press', value: 18, color: '#06b6d4' },
  { name: 'Reviews', value: 12, color: '#f59e0b' },
  { name: 'Blogs', value: 15, color: '#8b5cf6' },
  { name: 'Forums', value: 8, color: '#10b981' },
  { name: 'Other', value: 5, color: '#94a3b8' },
];

// ── Radar Data for Signal Index ──
export const radarData = [
  { metric: 'Sentiment', value: 68, fullMark: 100 },
  { metric: 'Visibility', value: 81, fullMark: 100 },
  { metric: 'Engagement', value: 72, fullMark: 100 },
  { metric: 'Authority', value: 65, fullMark: 100 },
  { metric: 'Momentum', value: 79, fullMark: 100 },
];
